server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 20480
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript

spring:
  application.name: "hs"
  profiles.active: dev
  datasource:
    url: jdbc:mysql://azhou.top:3306/hs?userUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1231
    initial-size: 1
    max-active: 10
    min-idle: 1
  redis:
    host: azhou.top
    port: 6379
    password:
    database: 0
    timeout: 3000
    pool:
      max-idle: 20
      min-idle: 5

#MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-locations: classpath:mybatis-config.xml
  type-aliases-package: com.hs.entity

